name: merge_control_cli
description: CLI utility for checking merge rules.
version: 1.1.0
repository: https://github.com/karbunkul/merge_control_cli

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  args: ^2.3.1
  path: ^1.8.2
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  merge-control: merge_control

