name: merge_control_cli
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  args: ^2.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  merge-control: merge_control

